steps:
- name: 'gcr.io/cloud-builders/docker-compose'
  args: ['build', '-f', 'docker-compose.yml']
  env:
  - PROJECT_ID: '${{ secrets.GCP_PROJECT_ID }}'
  - TAG: 'latest'
- name: 'gcr.io/cloud-builders/docker-compose'
  args: ['push']

options:
  logging: CLOUD_LOGGING_ONLY
