services:
  server:
    build:
      context: ./server
      image: ${PROJECT_ID}.cr.pkg.dev/us-central1/ricknmorty-server-repo/server:${TAG}
      dockerfile: server.Dockerfile

    ports:
      - "3000:3000"

  client:
    depends_on:
      - server
  
    build:
      context: ./client
      image: ${PROJECT_ID}.cr.pkg.dev/us-central1/ricknmorty-client-repo/client:${TAG}
      dockerfile: frontend.Dockerfile

    ports:
      - "4200:4200"
